IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetBCDuTruChiPhiDinhKyVTPT')
   exec('CREATE PROCEDURE spGetBCDuTruChiPhiDinhKyVTPT AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetBCDuTruChiPhiDinhKyVTPT
	@UserName NVARCHAR(50) ='admin',
	@NNgu INT =0,
	@TuNgay DATETIME =  '01/01/2024',
	@DenNgay DATETIME = '12/31/2024',
	@MsNhaXuong NVARCHAR(50) ='-1',
	@MsHeThong INT =-1,
	@MsLoaiMay nvarchar(50) ='-1'
AS
begin

--@LoaiBC = 0 Co xoa KHTT va PBT 
--@LoaiBC = 1 Khong xoa KHTT va PBT 


SELECT * INTO #MAY FROM dbo.MGetMayUserNgay(@TuNgay,@UserName,@MsNhaXuong,@MsHeThong,-1,@MsLoaiMay,'-1', '-1',@NNgu)  

SELECT     TOP (100) PERCENT T1.Ten_N_XUONG,A.MS_MAY,T1.TEN_MAY, A.MS_LOAI_BT, convert(varchar, A.NGAY_HC_CUOI, 103) AS NGAY_CUOI , A.CHU_KY, A.MS_DV_TG, A.NGAY_KE AS NGAY_BTKT INTO #HIEU_CHUAN_KE
FROM         dbo.MGetNgayHieuChuanKeBaoTri(@TuNgay, @DenNgay, @UserName, @MsNhaXuong, @MsHeThong, @MsLoaiMay, '-1', 1) AS A  INNER JOIN #MAY T1 ON T1.MS_MAY = A.MS_MAY
ORDER BY A.MS_MAY, A.MS_LOAI_BT, A.NGAY_HC_CUOI, A.CHU_KY, A.MS_DV_TG, A.NGAY_KE



--Xóa dữ liệu quan hệ trong khoảng 1/4 chu kỳ của bảo trì con
DELETE T1
FROM         dbo.LOAI_BAO_TRI_QH INNER JOIN
                      #HIEU_CHUAN_KE AS T1 ON dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CD = T1.MS_LOAI_BT INNER JOIN
                      #HIEU_CHUAN_KE AS T2 ON T1.MS_MAY = T2.MS_MAY AND dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CT = T2.MS_LOAI_BT 
WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY_BTKT 
AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) <= T2.NGAY_BTKT 
 
--Xóa dữ liệu quan hệ trong khoảng 1/4 chu kỳ của bảo trì con trong PBT
DELETE T1
FROM         dbo.LOAI_BAO_TRI_QH INNER JOIN
                      #HIEU_CHUAN_KE AS T1 ON dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CD = T1.MS_LOAI_BT INNER JOIN
                      PHIEU_BAO_TRI AS T2 ON T1.MS_MAY = T2.MS_MAY AND dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CT = T2.MS_LOAI_BT 
WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY_BD_KH 
AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) <= T2.NGAY_BD_KH

--Xóa dữ liệu quan hệ trong khoảng 1/4 chu kỳ của bảo trì con trong KHTT 
DELETE T1
FROM         dbo.LOAI_BAO_TRI_QH INNER JOIN
                      #HIEU_CHUAN_KE AS T1 ON dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CD = T1.MS_LOAI_BT INNER JOIN
                      KE_HOACH_TONG_THE AS T2 ON T1.MS_MAY = T2.MS_MAY AND dbo.LOAI_BAO_TRI_QH.MS_LOAI_BT_CT = T2.MS_LOAI_BT 
WHERE DATEADD(DAY, CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4, T1.NGAY_BTKT) >= T2.NGAY
AND DATEADD(DAY, - (CASE T1.MS_DV_TG WHEN 2 THEN T1.CHU_KY * 7 WHEN 3 THEN T1.CHU_KY * 30 WHEN 4 THEN T1.CHU_KY * 365 ELSE T1.CHU_KY END / 4), T1.NGAY_BTKT) <= T2.NGAY
--@LoaiBC = 0 Co xoa trong KHTT va PBT da lap
--@LoaiBC = 1 Khong xoa trong KHTT va PBT da lap


	SELECT A.Ten_N_XUONG,A.MS_MAY,A.TEN_MAY,A.NGAY_CUOI,A.NGAY_BTKT,B.MS_PT,D.TEN_PT,B.SO_LUONG,C.DON_GIA,ISNULL(B.SO_LUONG * C.DON_GIA,0) AS THANH_TIEN 
	INTO #TMPBTDK
	FROM #HIEU_CHUAN_KE A
	INNER JOIN dbo.MAY_LOAI_BTPN_CONG_VIEC_PHU_TUNG B ON B.MS_MAY = A.MS_MAY AND B.MS_LOAI_BT = A.MS_LOAI_BT
	INNER JOIN dbo.IC_PHU_TUNG D ON D.MS_PT = B.MS_PT
	INNER JOIN (
	SELECT MS_PT,MAX(DON_GIA) AS DON_GIA FROM dbo.IC_DON_HANG_NHAP_VAT_TU GROUP BY MS_PT ) AS C ON C.MS_PT = B.MS_PT

	--Cap nhap các may có ngay cuối nằm trong 1/4 chu ky về 1 màu 

	SELECT Ten_N_XUONG,
           MS_MAY,
           TEN_MAY,
           NGAY_CUOI,
           NGAY_BTKT,
           MS_PT,
           TEN_PT,
           SO_LUONG,
           DON_GIA,
           THANH_TIEN FROM #TMPBTDK  ORDER BY Ten_N_XUONG,MS_MAY,TEN_MAY,MS_PT

		   SELECT Ten_N_XUONG,SUM(THANH_TIEN) AS TONG_TIEN FROM #TMPBTDK GROUP BY Ten_N_XUONG 
		   ORDER BY Ten_N_XUONG
		  
END	
GO

