
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListDownTimeByDate')
exec('CREATE PROCEDURE spGetListDownTimeByDate AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetListDownTimeByDate]
	@USERNAME NVARCHAR(250) ='admin',
	@NNgu INT = 0,
	@LOAI_MAY NVARCHAR(30) = '-1',
	@MS_HETHONG NVARCHAR(30) = -1,
	@MS_NHA_XUONG NVARCHAR(30) = '-1',
	@TuNgay DATE = '10/19/2020',
	@DenNgay DATE  ='12/25/2021',
	@LOCK BIT
AS 
BEGIN
	
	SELECT DISTINCT * INTO #MAY_USER FROM dbo.MGetMayUserNgay(@DenNgay,@USERNAME,@MS_NHA_XUONG,@MS_HETHONG,-1,@LOAI_MAY,'-1','-1',@NNgu)  A 

	SELECT DISTINCT TGDM.MS_MAY, CAST(TGDM.NGAY AS DATE) AS NGAY
	FROM dbo.THOI_GIAN_NGUNG_MAY TGDM
	INNER JOIN #MAY_USER MAY ON MAY.MS_MAY = TGDM.MS_MAY
	WHERE CAST(TGDM.NGAY AS DATE) BETWEEN @TuNgay AND @DenNgay AND ISNULL(TGDM.LOCK,0) =@LOCK
	ORDER BY NGAY DESC, TGDM.MS_MAY
END	


