
-- GetMayBCChiPhi '01/01/2000' , '01/01/2014', -1,'-1','-1','-1', 'administrator',2
ALTER PROC [dbo].[GetMayBCChiPhi]
	@TNgay AS DATETIME,
	@DNgay AS DATETIME,
	@HThong AS INT,
	@NXuong AS NVARCHAR(50),
	@BPCPhi AS int,
	@MsLMay AS NVARCHAR(50),
	@MsNhomMay AS NVARCHAR(50),
	@UName AS NVARCHAR(50), 
	@LOAI AS INT = 0
AS
	DECLARE @NgayHT DATETIME
	SET @NgayHT = GETDATE()
	
IF @LOAI = 1	
	SELECT DISTINCT  A.MS_MAY , A.TEN_MAY    FROM
	(
	SELECT DISTINCT A.MS_N_XUONG AS MSNX, DBO.MGetHTTheoNgay (M.MS_MAY,@NgayHT) AS  MS_HT, 
	DBO.MGetBPCPhiTheoNgay(M.MS_MAY,@NgayHT) AS MSBP, M.MS_MAY,M.TEN_MAY 
		FROM MAY M INNER JOIN PHIEU_BAO_TRI N ON M.MS_MAY = N.MS_MAY INNER JOIN dbo.NHOM_MAY AS X ON 
		M.MS_NHOM_MAY = X.MS_NHOM_MAY INNER JOIN dbo.LOAI_MAY AS Y ON X.MS_LOAI_MAY = Y.MS_LOAI_MAY
		INNER JOIN (SELECT * FROM [dbo].[MGetNXMayUserDiaDiem]('-1',@NXuong,@NgayHT,@UName,'-1','-1','-1') ) A
		ON A.MS_MAY = M.MS_MAY INNER JOIN dbo.PHIEU_BAO_TRI_CHI_PHI AS C ON N.MS_PHIEU_BAO_TRI = C.MS_PHIEU_BAO_TRI			
	WHERE (TINH_TRANG_PBT > 3) AND (NGAY_BD_KH BETWEEN @TNgay AND DATEADD(DAY,1,@DNgay) ) AND 
		(@MsLMay = '-1' OR X.MS_LOAI_MAY = @MSLMAY)   AND	(@MsNhomMay = '-1' OR  M.MS_NHOM_MAY = @MsNhomMay) 
	) A INNER JOIN (SELECT MS_N_XUONG FROM [dbo].[MGetNhaXuongDiaDiem]('-1','-1','-1',@UName) ) B 
	ON A.MSNX = B.MS_N_XUONG 
	WHERE (@HThong = -1 OR MS_HT = @HThong)   AND	(@BPCPhi = -1 OR MSBP = @BPCPhi)   
	
	UNION SELECT ' < ALL > ' , ' < ALL > '
	--ORDER BY A.MS_MAY	,A.TEN_MAY
ELSE
	SELECT DISTINCT  A.MS_MAY, TEN_MAY, MODEL, C.TEN_NHOM_MAY, D.TEN_LOAI_MAY    FROM
	(
	SELECT DISTINCT A.MS_N_XUONG AS MSNX, DBO.MGetHTTheoNgay (M.MS_MAY,@NgayHT) AS  MS_HT, 
	DBO.MGetBPCPhiTheoNgay(M.MS_MAY,@NgayHT) AS MSBP, M.MS_MAY,M.TEN_MAY,M.MODEL,M.MS_NHOM_MAY
		FROM MAY M INNER JOIN PHIEU_BAO_TRI N ON M.MS_MAY = N.MS_MAY INNER JOIN dbo.NHOM_MAY AS X ON 
		M.MS_NHOM_MAY = X.MS_NHOM_MAY INNER JOIN dbo.LOAI_MAY AS Y ON X.MS_LOAI_MAY = Y.MS_LOAI_MAY
		INNER JOIN (SELECT * FROM [dbo].[MGetNXMayUserDiaDiem]('-1',@NXuong,@NgayHT,@UName,'-1','-1','-1') ) A
		ON A.MS_MAY = M.MS_MAY INNER JOIN dbo.PHIEU_BAO_TRI_CHI_PHI AS C ON N.MS_PHIEU_BAO_TRI = C.MS_PHIEU_BAO_TRI			
	--WHERE (TINH_TRANG_PBT > 3) AND (NGAY_BD_KH BETWEEN @TNgay AND DATEADD(DAY,1,@DNgay)) AND 
	--	(@MsLMay = '-1' OR X.MS_LOAI_MAY = @MSLMAY)   AND	(@MsNhomMay = '-1' OR  M.MS_NHOM_MAY = @MsNhomMay)   
	) A INNER JOIN (SELECT MS_N_XUONG FROM [dbo].[MGetNhaXuongDiaDiem]('-1','-1','-1',@UName) ) B 
	ON A.MSNX = B.MS_N_XUONG INNER JOIN NHOM_MAY  C ON A.MS_NHOM_MAY = C.MS_NHOM_MAY INNER JOIN
	LOAI_MAY D ON C.MS_LOAI_MAY = D.MS_LOAI_MAY 
	WHERE (@HThong = -1 OR MS_HT = @HThong)   AND	(@BPCPhi = -1 OR MSBP = @BPCPhi)   
	
	ORDER BY A.MS_MAY	
