
--INSERT INTO dbo.TRANG_THAI_PSDV(MS_TRANG_THAI,TEN_TRANG_THAI,GHI_CHU)VALUES(7,N'Chờ duyệt',N'')
--INSERT INTO dbo.TRANG_THAI_PSDV(MS_TRANG_THAI,TEN_TRANG_THAI,GHI_CHU)VALUES(8,N'Không được duyệt',N'')
--UPDATE dbo.TRANG_THAI_PSDV SET TEN_TRANG_THAI = N'Đã gửi BC365' WHERE MS_TRANG_THAI =3

--CREATE TABLE [dbo].[DIEU_KIEN_DUYET_PSDV]
--(
--[MS_DUYET] [nvarchar] (10)  NOT NULL,
--[LOAI] [int] NULL,
--[TEN] [nvarchar] (50)  NULL
--) ON [PRIMARY]
--GO
--ALTER TABLE [dbo].[DIEU_KIEN_DUYET_PSDV] ADD CONSTRAINT [PK_DIEU_KIEN_DUYET_PSDV] PRIMARY KEY CLUSTERED ([MS_DUYET]) ON [PRIMARY]
--GO
--ALTER TABLE dbo.PHAT_SINH_DICH_VU ADD USER_DUYET NVARCHAR(50) 


