IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spSaveThoiGianNgungMay')
exec('CREATE PROCEDURE spSaveThoiGianNgungMay AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spSaveThoiGianNgungMay]
    @ID BIGINT,
	@ID_CHA BIGINT,
    @MS_MAY NVARCHAR(30) ,
    @MS_NGUYEN_NHAN INT ,
	@NGUYEN_NHAN NVARCHAR(250),
	@NGUYEN_NHAN_CU_THE NVARCHAR(250),
	@HIEN_TUONG NVARCHAR(250),
	@GHI_CHU NVARCHAR(500),
	@TRUONG_CA NVARCHAR(250),
	@NGUOI_GIAI_QUYET NVARCHAR(250),
	@MS_PHIEU_BAO_TRI NVARCHAR(250),
	@MS_TO INT,
	@THOI_GIAN_SUA FLOAT,
	@THOI_GIAN_SUA_CHUA FLOAT,
	@sBTNgay NVARCHAR(250),
	@sBTPT NVARCHAR(250)

AS
    BEGIN
		CREATE TABLE #TEMPT_TG (
		[NGAY] [datetime] NULL,
		[TU_GIO] [datetime] NULL,
		[DEN_NGAY] [datetime] NULL,
		[DEN_GIO] [datetime] NULL,
		[CaID] [int] NULL
		) ON [PRIMARY]


		CREATE TABLE #TEMPT_PT (
		[MS_MAY] [nvarchar] (30)  NULL,
		[STT] [int] NULL,
		[MS_BO_PHAN] [nvarchar] (50)  NULL,
		[MS_PT] [nvarchar] (50)  NULL,
		[MS_VI_TRI_PT] [nvarchar] (30)  NULL
		) ON [PRIMARY]


		DECLARE @sSql nvarchar(4000)
		set @sSql = 'INSERT INTO #TEMPT_TG(NGAY,TU_GIO,DEN_NGAY,DEN_GIO,CaID)SELECT NGAY,TU_GIO,DEN_NGAY,DEN_GIO,CaID FROM '+ @sBTNgay
		EXEC (@sSql)
		set @sSql = 'DROP TABLE ' + @sBTNgay
		EXEC (@sSql)

		SET @sSql = 'INSERT INTO #TEMPT_PT(MS_MAY,STT,MS_BO_PHAN,MS_PT,MS_VI_TRI_PT)SELECT  MS_MAY,STT,MS_BO_PHAN,MS_PT,MS_VI_TRI_PT  FROM  '+ @sBTPT
		EXEC (@sSql)
		set @sSql = 'DROP TABLE ' + @sBTPT
		EXEC (@sSql)

		  IF @ID = -1
		  BEGIN
			
			IF @ID = -1
			DECLARE @ngay DATETIME
			WHILE((SELECT COUNT(*) FROM #TEMPT_TG) > 0)
			BEGIN
				 SELECT TOP 1  @ngay = NGAY + CONVERT(NVARCHAR(20),TU_GIO,114) FROM #TEMPT_TG
		
				DECLARE @MS_CHA BIGINT;
				SET @MS_CHA = CASE WHEN @ID_CHA > 0 THEN @ID_CHA else (SELECT TOP 1 ID FROM dbo.THOI_GIAN_NGUNG_MAY WHERE  (DEN_NGAY + DEN_GIO = @ngay) AND  MS_MAY =@MS_MAY) END
				INSERT INTO dbo.THOI_GIAN_NGUNG_MAY
				(MS_MAY,NGAY,TU_GIO,DEN_NGAY,DEN_GIO,MS_NGUYEN_NHAN,GHI_CHU,TRUONG_CA,NGUOI_GIAI_QUYET,MS_HE_THONG,MS_N_XUONG,THOI_GIAN_SUA_CHUA,
				THOI_GIAN_SUA,NGUYEN_NHAN,NGUYEN_NHAN_CU_THE,HIEN_TUONG,CaID,MS_PHIEU_BAO_TRI,MS_TO,ID_CHA)

				SELECT @MS_MAY,NGAY,'1900-01-01 ' + CONVERT(NVARCHAR(20),TU_GIO,114),DEN_NGAY,'1900-01-01 ' + CONVERT(NVARCHAR(20),DEN_GIO,114),@MS_NGUYEN_NHAN,@GHI_CHU,@TRUONG_CA,@NGUOI_GIAI_QUYET,(SELECT MS_HE_THONG FROM dbo.MAY_HE_THONG WHERE MS_MAY =@MS_MAY),(SELECT MS_N_XUONG FROM dbo.MAY_NHA_XUONG WHERE MS_MAY =@MS_MAY),DATEDIFF(MINUTE,NGAY+CONVERT(NVARCHAR(20),TU_GIO,114),DEN_NGAY+CONVERT(NVARCHAR(20),DEN_GIO,114)),
				DATEDIFF(MINUTE,NGAY+CONVERT(NVARCHAR(20),TU_GIO,114),DEN_NGAY+CONVERT(NVARCHAR(20),DEN_GIO,114)),@NGUYEN_NHAN,@NGUYEN_NHAN_CU_THE,@HIEN_TUONG,CaID,@MS_PHIEU_BAO_TRI,@MS_TO,@MS_CHA FROM #TEMPT_TG WHERE  NGAY + CONVERT(NVARCHAR(20),TU_GIO,114) = @ngay

				INSERT INTO dbo.THOI_GIAN_NGUNG_MAY_PHU_TUNG(MS_MAY,MS_BO_PHAN,MS_PT,MS_VI_TRI_PT,ID_TGNM)
				SELECT @MS_MAY,MS_BO_PHAN,MS_PT,MS_VI_TRI_PT,SCOPE_IDENTITY() FROM #TEMPT_PT

				DELETE #TEMPT_TG WHERE  NGAY + CONVERT(NVARCHAR(20),TU_GIO,114)  = @ngay

				SET @ID = SCOPE_IDENTITY()

				END
			END
			ELSE

			BEGIN
				--lấy tất cả các nguyên nhân có liên quan
			 
				 UPDATE dbo.THOI_GIAN_NGUNG_MAY 
				 SET MS_NGUYEN_NHAN =@MS_NGUYEN_NHAN,
				 TRUONG_CA =@TRUONG_CA,
				 GHI_CHU =@GHI_CHU,
				 NGUOI_GIAI_QUYET =@NGUOI_GIAI_QUYET,
				 NGUYEN_NHAN_CU_THE =@NGUYEN_NHAN_CU_THE,
				 HIEN_TUONG = @HIEN_TUONG,
				 MS_PHIEU_BAO_TRI =@MS_PHIEU_BAO_TRI,
				 MS_TO =@MS_TO
				 WHERE ID IN(SELECT * FROM dbo.fnGetNguyenNhanNM(@ID))

				 UPDATE dbo.THOI_GIAN_NGUNG_MAY SET
				 NGAY = (SELECT TOP 1 NGAY FROM #TEMPT_TG),
				 TU_GIO = (SELECT TOP 1 '1900-01-01 ' + CONVERT(NVARCHAR(20),TU_GIO,114) FROM #TEMPT_TG),
				 DEN_NGAY = (SELECT TOP 1 DEN_NGAY FROM #TEMPT_TG),
				 DEN_GIO = (SELECT TOP 1 '1900-01-01 ' + CONVERT(NVARCHAR(20),DEN_GIO,114) FROM #TEMPT_TG),
				 THOI_GIAN_SUA = @THOI_GIAN_SUA,
				 THOI_GIAN_SUA_CHUA =@THOI_GIAN_SUA_CHUA
				 WHERE ID = @ID

				 --insert vào những thèn nào chưa tồn tại
				 
				 SELECT B.MS_MAY,B.STT,B.MS_BO_PHAN,B.MS_PT,B.MS_VI_TRI_PT,A.MS_NM
				 INTO #TMP
				 FROM dbo.fnGetNguyenNhanNM(@ID) A INNER JOIN #TEMPT_PT B ON 1= 1


				 INSERT INTO dbo.THOI_GIAN_NGUNG_MAY_PHU_TUNG
				 (
				     MS_MAY,
				     MS_BO_PHAN,
				     MS_PT,
				     MS_VI_TRI_PT,
				     ID_TGNM
				 )
				SELECT T.MS_MAY,T.MS_BO_PHAN,T.MS_PT,T.MS_VI_TRI_PT,T.MS_NM FROM #TMP T
				WHERE NOT EXISTS (SELECT * FROM dbo.THOI_GIAN_NGUNG_MAY_PHU_TUNG B WHERE T.MS_MAY = B.MS_MAY AND T.MS_NM = B.ID_TGNM AND T.MS_BO_PHAN = B.MS_BO_PHAN)

				UPDATE A
				SET A.MS_PT =B.MS_PT,A.MS_VI_TRI_PT =B.MS_VI_TRI_PT
				FROM dbo.THOI_GIAN_NGUNG_MAY_PHU_TUNG A
				INNER JOIN #TMP B ON B.STT = A.STT
				WHERE B.STT != -1
			END
			SELECT @ID
    END
	



