		ALTER TABLE THONG_TIN_CHUNG ALTER COLUMN  Phone NVARCHAR(50)
		ALTER TABLE THONG_TIN_CHUNG ALTER COLUMN  Fax NVARCHAR(50)

		ALTER TABLE W_THONG_TIN_CHUNG ALTER COLUMN  Phone NVARCHAR(50)
		ALTER TABLE W_THONG_TIN_CHUNG ALTER COLUMN  Fax NVARCHAR(50)