#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInfoReport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CMMS_Ecomaint")]
	public partial class CustomInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNHA_XUONG(NHA_XUONG instance);
    partial void UpdateNHA_XUONG(NHA_XUONG instance);
    partial void DeleteNHA_XUONG(NHA_XUONG instance);
    partial void InsertNHOM_MAY(NHOM_MAY instance);
    partial void UpdateNHOM_MAY(NHOM_MAY instance);
    partial void DeleteNHOM_MAY(NHOM_MAY instance);
    partial void InsertLOAI_MAY(LOAI_MAY instance);
    partial void UpdateLOAI_MAY(LOAI_MAY instance);
    partial void DeleteLOAI_MAY(LOAI_MAY instance);
    partial void InsertIC_DUONG(IC_DUONG instance);
    partial void UpdateIC_DUONG(IC_DUONG instance);
    partial void DeleteIC_DUONG(IC_DUONG instance);
    partial void InsertLOAI_BAO_TRI(LOAI_BAO_TRI instance);
    partial void UpdateLOAI_BAO_TRI(LOAI_BAO_TRI instance);
    partial void DeleteLOAI_BAO_TRI(LOAI_BAO_TRI instance);
    #endregion
		
		public CustomInfoDataContext() : 
				base(global::CustomerInfoReport.Properties.Settings.Default.CMMS_EcomaintConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Y_Tinh> Y_Tinhs
		{
			get
			{
				return this.GetTable<Y_Tinh>();
			}
		}
		
		public System.Data.Linq.Table<Y_District> Y_Districts
		{
			get
			{
				return this.GetTable<Y_District>();
			}
		}
		
		public System.Data.Linq.Table<NHA_XUONG> NHA_XUONGs
		{
			get
			{
				return this.GetTable<NHA_XUONG>();
			}
		}
		
		public System.Data.Linq.Table<NHOM_MAY> NHOM_MAYs
		{
			get
			{
				return this.GetTable<NHOM_MAY>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_MAY> LOAI_MAYs
		{
			get
			{
				return this.GetTable<LOAI_MAY>();
			}
		}
		
		public System.Data.Linq.Table<Y_Duong> Y_Duongs
		{
			get
			{
				return this.GetTable<Y_Duong>();
			}
		}
		
		public System.Data.Linq.Table<IC_DUONG> IC_DUONGs
		{
			get
			{
				return this.GetTable<IC_DUONG>();
			}
		}
		
		public System.Data.Linq.Table<View_Duong_Not_District> View_Duong_Not_Districts
		{
			get
			{
				return this.GetTable<View_Duong_Not_District>();
			}
		}
		
		public System.Data.Linq.Table<V_ReportCustomer> V_ReportCustomers
		{
			get
			{
				return this.GetTable<V_ReportCustomer>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_BAO_TRI> LOAI_BAO_TRIs
		{
			get
			{
				return this.GetTable<LOAI_BAO_TRI>();
			}
		}
		
		public System.Data.Linq.Table<V_Report_Warranty_Equipment> V_Report_Warranty_Equipments
		{
			get
			{
				return this.GetTable<V_Report_Warranty_Equipment>();
			}
		}
		
		public System.Data.Linq.Table<V_ReportMaintaince> V_ReportMaintainces
		{
			get
			{
				return this.GetTable<V_ReportMaintaince>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_Nha_Xuong_All")]
		public ISingleResult<Get_Nha_Xuong_AllResult> Get_Nha_Xuong_All([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string ms_tinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string ms_quan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string ms_duong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ms_tinh, ms_quan, ms_duong);
			return ((ISingleResult<Get_Nha_Xuong_AllResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Y_Tinh")]
	public partial class Y_Tinh
	{
		
		private string _ma_qg;
		
		private string _ten_qg;
		
		public Y_Tinh()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_qg", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ma_qg
		{
			get
			{
				return this._ma_qg;
			}
			set
			{
				if ((this._ma_qg != value))
				{
					this._ma_qg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_qg", DbType="NVarChar(100)")]
		public string ten_qg
		{
			get
			{
				return this._ten_qg;
			}
			set
			{
				if ((this._ten_qg != value))
				{
					this._ten_qg = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Y_District")]
	public partial class Y_District
	{
		
		private string _ma_qg;
		
		private string _ten_qg;
		
		private string _ms_cha;
		
		public Y_District()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_qg", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ma_qg
		{
			get
			{
				return this._ma_qg;
			}
			set
			{
				if ((this._ma_qg != value))
				{
					this._ma_qg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_qg", DbType="NVarChar(100)")]
		public string ten_qg
		{
			get
			{
				return this._ten_qg;
			}
			set
			{
				if ((this._ten_qg != value))
				{
					this._ten_qg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_cha", DbType="NVarChar(30)")]
		public string ms_cha
		{
			get
			{
				return this._ms_cha;
			}
			set
			{
				if ((this._ms_cha != value))
				{
					this._ms_cha = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHA_XUONG")]
	public partial class NHA_XUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MS_N_XUONG;
		
		private string _MS_CHA;
		
		private string _TEN_N_XUONG;
		
		private string _TEN_N_XUONG_A;
		
		private string _TEN_N_XUONG_H;
		
		private string _TRU_SO;
		
		private string _NGUOI_DAI_DIEN;
		
		private string _DIEN_THOAI;
		
		private string _MS_QG;
		
		private string _MS_DUONG;
		
		private string _DIA_CHI;
		
		private System.Nullable<double> _DIEN_TICH;
		
		private System.Nullable<double> _KHOANG_CACH;
		
		private string _GHI_CHU;
		
		private string _MS_DON_VI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMS_N_XUONGChanging(string value);
    partial void OnMS_N_XUONGChanged();
    partial void OnMS_CHAChanging(string value);
    partial void OnMS_CHAChanged();
    partial void OnTEN_N_XUONGChanging(string value);
    partial void OnTEN_N_XUONGChanged();
    partial void OnTEN_N_XUONG_AChanging(string value);
    partial void OnTEN_N_XUONG_AChanged();
    partial void OnTEN_N_XUONG_HChanging(string value);
    partial void OnTEN_N_XUONG_HChanged();
    partial void OnTRU_SOChanging(string value);
    partial void OnTRU_SOChanged();
    partial void OnNGUOI_DAI_DIENChanging(string value);
    partial void OnNGUOI_DAI_DIENChanged();
    partial void OnDIEN_THOAIChanging(string value);
    partial void OnDIEN_THOAIChanged();
    partial void OnMS_QGChanging(string value);
    partial void OnMS_QGChanged();
    partial void OnMS_DUONGChanging(string value);
    partial void OnMS_DUONGChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    partial void OnDIEN_TICHChanging(System.Nullable<double> value);
    partial void OnDIEN_TICHChanged();
    partial void OnKHOANG_CACHChanging(System.Nullable<double> value);
    partial void OnKHOANG_CACHChanged();
    partial void OnGHI_CHUChanging(string value);
    partial void OnGHI_CHUChanged();
    partial void OnMS_DON_VIChanging(string value);
    partial void OnMS_DON_VIChanged();
    #endregion
		
		public NHA_XUONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_N_XUONG", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MS_N_XUONG
		{
			get
			{
				return this._MS_N_XUONG;
			}
			set
			{
				if ((this._MS_N_XUONG != value))
				{
					this.OnMS_N_XUONGChanging(value);
					this.SendPropertyChanging();
					this._MS_N_XUONG = value;
					this.SendPropertyChanged("MS_N_XUONG");
					this.OnMS_N_XUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_CHA", DbType="NVarChar(5)")]
		public string MS_CHA
		{
			get
			{
				return this._MS_CHA;
			}
			set
			{
				if ((this._MS_CHA != value))
				{
					this.OnMS_CHAChanging(value);
					this.SendPropertyChanging();
					this._MS_CHA = value;
					this.SendPropertyChanged("MS_CHA");
					this.OnMS_CHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_N_XUONG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_N_XUONG
		{
			get
			{
				return this._TEN_N_XUONG;
			}
			set
			{
				if ((this._TEN_N_XUONG != value))
				{
					this.OnTEN_N_XUONGChanging(value);
					this.SendPropertyChanging();
					this._TEN_N_XUONG = value;
					this.SendPropertyChanged("TEN_N_XUONG");
					this.OnTEN_N_XUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_N_XUONG_A", DbType="NVarChar(100)")]
		public string TEN_N_XUONG_A
		{
			get
			{
				return this._TEN_N_XUONG_A;
			}
			set
			{
				if ((this._TEN_N_XUONG_A != value))
				{
					this.OnTEN_N_XUONG_AChanging(value);
					this.SendPropertyChanging();
					this._TEN_N_XUONG_A = value;
					this.SendPropertyChanged("TEN_N_XUONG_A");
					this.OnTEN_N_XUONG_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_N_XUONG_H", DbType="NVarChar(100)")]
		public string TEN_N_XUONG_H
		{
			get
			{
				return this._TEN_N_XUONG_H;
			}
			set
			{
				if ((this._TEN_N_XUONG_H != value))
				{
					this.OnTEN_N_XUONG_HChanging(value);
					this.SendPropertyChanging();
					this._TEN_N_XUONG_H = value;
					this.SendPropertyChanged("TEN_N_XUONG_H");
					this.OnTEN_N_XUONG_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRU_SO", DbType="NVarChar(100)")]
		public string TRU_SO
		{
			get
			{
				return this._TRU_SO;
			}
			set
			{
				if ((this._TRU_SO != value))
				{
					this.OnTRU_SOChanging(value);
					this.SendPropertyChanging();
					this._TRU_SO = value;
					this.SendPropertyChanged("TRU_SO");
					this.OnTRU_SOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOI_DAI_DIEN", DbType="NVarChar(100)")]
		public string NGUOI_DAI_DIEN
		{
			get
			{
				return this._NGUOI_DAI_DIEN;
			}
			set
			{
				if ((this._NGUOI_DAI_DIEN != value))
				{
					this.OnNGUOI_DAI_DIENChanging(value);
					this.SendPropertyChanging();
					this._NGUOI_DAI_DIEN = value;
					this.SendPropertyChanged("NGUOI_DAI_DIEN");
					this.OnNGUOI_DAI_DIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEN_THOAI", DbType="NVarChar(20)")]
		public string DIEN_THOAI
		{
			get
			{
				return this._DIEN_THOAI;
			}
			set
			{
				if ((this._DIEN_THOAI != value))
				{
					this.OnDIEN_THOAIChanging(value);
					this.SendPropertyChanging();
					this._DIEN_THOAI = value;
					this.SendPropertyChanged("DIEN_THOAI");
					this.OnDIEN_THOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_QG", DbType="NVarChar(30)")]
		public string MS_QG
		{
			get
			{
				return this._MS_QG;
			}
			set
			{
				if ((this._MS_QG != value))
				{
					this.OnMS_QGChanging(value);
					this.SendPropertyChanging();
					this._MS_QG = value;
					this.SendPropertyChanged("MS_QG");
					this.OnMS_QGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_DUONG", DbType="NVarChar(30)")]
		public string MS_DUONG
		{
			get
			{
				return this._MS_DUONG;
			}
			set
			{
				if ((this._MS_DUONG != value))
				{
					this.OnMS_DUONGChanging(value);
					this.SendPropertyChanging();
					this._MS_DUONG = value;
					this.SendPropertyChanged("MS_DUONG");
					this.OnMS_DUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(100)")]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEN_TICH", DbType="Float")]
		public System.Nullable<double> DIEN_TICH
		{
			get
			{
				return this._DIEN_TICH;
			}
			set
			{
				if ((this._DIEN_TICH != value))
				{
					this.OnDIEN_TICHChanging(value);
					this.SendPropertyChanging();
					this._DIEN_TICH = value;
					this.SendPropertyChanged("DIEN_TICH");
					this.OnDIEN_TICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOANG_CACH", DbType="Float")]
		public System.Nullable<double> KHOANG_CACH
		{
			get
			{
				return this._KHOANG_CACH;
			}
			set
			{
				if ((this._KHOANG_CACH != value))
				{
					this.OnKHOANG_CACHChanging(value);
					this.SendPropertyChanging();
					this._KHOANG_CACH = value;
					this.SendPropertyChanged("KHOANG_CACH");
					this.OnKHOANG_CACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(200)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this.OnGHI_CHUChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHU = value;
					this.SendPropertyChanged("GHI_CHU");
					this.OnGHI_CHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_DON_VI", DbType="NVarChar(6)")]
		public string MS_DON_VI
		{
			get
			{
				return this._MS_DON_VI;
			}
			set
			{
				if ((this._MS_DON_VI != value))
				{
					this.OnMS_DON_VIChanging(value);
					this.SendPropertyChanging();
					this._MS_DON_VI = value;
					this.SendPropertyChanged("MS_DON_VI");
					this.OnMS_DON_VIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHOM_MAY")]
	public partial class NHOM_MAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MS_NHOM_MAY;
		
		private string _TEN_NHOM_MAY;
		
		private string _MS_LOAI_MAY;
		
		private EntityRef<LOAI_MAY> _LOAI_MAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMS_NHOM_MAYChanging(string value);
    partial void OnMS_NHOM_MAYChanged();
    partial void OnTEN_NHOM_MAYChanging(string value);
    partial void OnTEN_NHOM_MAYChanged();
    partial void OnMS_LOAI_MAYChanging(string value);
    partial void OnMS_LOAI_MAYChanged();
    #endregion
		
		public NHOM_MAY()
		{
			this._LOAI_MAY = default(EntityRef<LOAI_MAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_NHOM_MAY", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MS_NHOM_MAY
		{
			get
			{
				return this._MS_NHOM_MAY;
			}
			set
			{
				if ((this._MS_NHOM_MAY != value))
				{
					this.OnMS_NHOM_MAYChanging(value);
					this.SendPropertyChanging();
					this._MS_NHOM_MAY = value;
					this.SendPropertyChanged("MS_NHOM_MAY");
					this.OnMS_NHOM_MAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NHOM_MAY", DbType="NVarChar(250)")]
		public string TEN_NHOM_MAY
		{
			get
			{
				return this._TEN_NHOM_MAY;
			}
			set
			{
				if ((this._TEN_NHOM_MAY != value))
				{
					this.OnTEN_NHOM_MAYChanging(value);
					this.SendPropertyChanging();
					this._TEN_NHOM_MAY = value;
					this.SendPropertyChanged("TEN_NHOM_MAY");
					this.OnTEN_NHOM_MAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_LOAI_MAY", DbType="NVarChar(20)")]
		public string MS_LOAI_MAY
		{
			get
			{
				return this._MS_LOAI_MAY;
			}
			set
			{
				if ((this._MS_LOAI_MAY != value))
				{
					if (this._LOAI_MAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMS_LOAI_MAYChanging(value);
					this.SendPropertyChanging();
					this._MS_LOAI_MAY = value;
					this.SendPropertyChanged("MS_LOAI_MAY");
					this.OnMS_LOAI_MAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_MAY_NHOM_MAY", Storage="_LOAI_MAY", ThisKey="MS_LOAI_MAY", OtherKey="MS_LOAI_MAY", IsForeignKey=true)]
		public LOAI_MAY LOAI_MAY
		{
			get
			{
				return this._LOAI_MAY.Entity;
			}
			set
			{
				LOAI_MAY previousValue = this._LOAI_MAY.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_MAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_MAY.Entity = null;
						previousValue.NHOM_MAYs.Remove(this);
					}
					this._LOAI_MAY.Entity = value;
					if ((value != null))
					{
						value.NHOM_MAYs.Add(this);
						this._MS_LOAI_MAY = value.MS_LOAI_MAY;
					}
					else
					{
						this._MS_LOAI_MAY = default(string);
					}
					this.SendPropertyChanged("LOAI_MAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_MAY")]
	public partial class LOAI_MAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MS_LOAI_MAY;
		
		private string _TEN_LOAI_MAY;
		
		private System.Nullable<int> _STT_MAY;
		
		private System.Nullable<bool> _ATTACHMENT;
		
		private EntitySet<NHOM_MAY> _NHOM_MAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMS_LOAI_MAYChanging(string value);
    partial void OnMS_LOAI_MAYChanged();
    partial void OnTEN_LOAI_MAYChanging(string value);
    partial void OnTEN_LOAI_MAYChanged();
    partial void OnSTT_MAYChanging(System.Nullable<int> value);
    partial void OnSTT_MAYChanged();
    partial void OnATTACHMENTChanging(System.Nullable<bool> value);
    partial void OnATTACHMENTChanged();
    #endregion
		
		public LOAI_MAY()
		{
			this._NHOM_MAYs = new EntitySet<NHOM_MAY>(new Action<NHOM_MAY>(this.attach_NHOM_MAYs), new Action<NHOM_MAY>(this.detach_NHOM_MAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_LOAI_MAY", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MS_LOAI_MAY
		{
			get
			{
				return this._MS_LOAI_MAY;
			}
			set
			{
				if ((this._MS_LOAI_MAY != value))
				{
					this.OnMS_LOAI_MAYChanging(value);
					this.SendPropertyChanging();
					this._MS_LOAI_MAY = value;
					this.SendPropertyChanged("MS_LOAI_MAY");
					this.OnMS_LOAI_MAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI_MAY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEN_LOAI_MAY
		{
			get
			{
				return this._TEN_LOAI_MAY;
			}
			set
			{
				if ((this._TEN_LOAI_MAY != value))
				{
					this.OnTEN_LOAI_MAYChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAI_MAY = value;
					this.SendPropertyChanged("TEN_LOAI_MAY");
					this.OnTEN_LOAI_MAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT_MAY", DbType="Int")]
		public System.Nullable<int> STT_MAY
		{
			get
			{
				return this._STT_MAY;
			}
			set
			{
				if ((this._STT_MAY != value))
				{
					this.OnSTT_MAYChanging(value);
					this.SendPropertyChanging();
					this._STT_MAY = value;
					this.SendPropertyChanged("STT_MAY");
					this.OnSTT_MAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTACHMENT", DbType="Bit")]
		public System.Nullable<bool> ATTACHMENT
		{
			get
			{
				return this._ATTACHMENT;
			}
			set
			{
				if ((this._ATTACHMENT != value))
				{
					this.OnATTACHMENTChanging(value);
					this.SendPropertyChanging();
					this._ATTACHMENT = value;
					this.SendPropertyChanged("ATTACHMENT");
					this.OnATTACHMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_MAY_NHOM_MAY", Storage="_NHOM_MAYs", ThisKey="MS_LOAI_MAY", OtherKey="MS_LOAI_MAY")]
		public EntitySet<NHOM_MAY> NHOM_MAYs
		{
			get
			{
				return this._NHOM_MAYs;
			}
			set
			{
				this._NHOM_MAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHOM_MAYs(NHOM_MAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_MAY = this;
		}
		
		private void detach_NHOM_MAYs(NHOM_MAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_MAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Y_Duong")]
	public partial class Y_Duong
	{
		
		private string _Duong_Quan;
		
		private string _Duong_TV;
		
		private string _Duong_TA;
		
		private string _Duong_TH;
		
		private string _MS_Duong;
		
		private string _MS_Quan;
		
		private string _Quan;
		
		private string _MS_Tinh;
		
		public Y_Duong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duong_Quan", DbType="NVarChar(203)")]
		public string Duong_Quan
		{
			get
			{
				return this._Duong_Quan;
			}
			set
			{
				if ((this._Duong_Quan != value))
				{
					this._Duong_Quan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duong_TV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Duong_TV
		{
			get
			{
				return this._Duong_TV;
			}
			set
			{
				if ((this._Duong_TV != value))
				{
					this._Duong_TV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duong_TA", DbType="NVarChar(100)")]
		public string Duong_TA
		{
			get
			{
				return this._Duong_TA;
			}
			set
			{
				if ((this._Duong_TA != value))
				{
					this._Duong_TA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duong_TH", DbType="NVarChar(100)")]
		public string Duong_TH
		{
			get
			{
				return this._Duong_TH;
			}
			set
			{
				if ((this._Duong_TH != value))
				{
					this._Duong_TH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_Duong", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MS_Duong
		{
			get
			{
				return this._MS_Duong;
			}
			set
			{
				if ((this._MS_Duong != value))
				{
					this._MS_Duong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_Quan", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MS_Quan
		{
			get
			{
				return this._MS_Quan;
			}
			set
			{
				if ((this._MS_Quan != value))
				{
					this._MS_Quan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="NVarChar(100)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this._Quan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_Tinh", DbType="NVarChar(100)")]
		public string MS_Tinh
		{
			get
			{
				return this._MS_Tinh;
			}
			set
			{
				if ((this._MS_Tinh != value))
				{
					this._MS_Tinh = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IC_DUONG")]
	public partial class IC_DUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MS;
		
		private string _TEN_V;
		
		private string _TEN_A;
		
		private string _TEN_H;
		
		private string _GHI_CHU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSChanging(string value);
    partial void OnMSChanged();
    partial void OnTEN_VChanging(string value);
    partial void OnTEN_VChanged();
    partial void OnTEN_AChanging(string value);
    partial void OnTEN_AChanged();
    partial void OnTEN_HChanging(string value);
    partial void OnTEN_HChanged();
    partial void OnGHI_CHUChanging(string value);
    partial void OnGHI_CHUChanged();
    #endregion
		
		public IC_DUONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MS
		{
			get
			{
				return this._MS;
			}
			set
			{
				if ((this._MS != value))
				{
					this.OnMSChanging(value);
					this.SendPropertyChanging();
					this._MS = value;
					this.SendPropertyChanged("MS");
					this.OnMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_V", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_V
		{
			get
			{
				return this._TEN_V;
			}
			set
			{
				if ((this._TEN_V != value))
				{
					this.OnTEN_VChanging(value);
					this.SendPropertyChanging();
					this._TEN_V = value;
					this.SendPropertyChanged("TEN_V");
					this.OnTEN_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_A", DbType="NVarChar(100)")]
		public string TEN_A
		{
			get
			{
				return this._TEN_A;
			}
			set
			{
				if ((this._TEN_A != value))
				{
					this.OnTEN_AChanging(value);
					this.SendPropertyChanging();
					this._TEN_A = value;
					this.SendPropertyChanged("TEN_A");
					this.OnTEN_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_H", DbType="NVarChar(100)")]
		public string TEN_H
		{
			get
			{
				return this._TEN_H;
			}
			set
			{
				if ((this._TEN_H != value))
				{
					this.OnTEN_HChanging(value);
					this.SendPropertyChanging();
					this._TEN_H = value;
					this.SendPropertyChanged("TEN_H");
					this.OnTEN_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(200)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this.OnGHI_CHUChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHU = value;
					this.SendPropertyChanged("GHI_CHU");
					this.OnGHI_CHUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Duong_Not_District")]
	public partial class View_Duong_Not_District
	{
		
		private string _ten_v;
		
		private string _ms_Duong;
		
		private string _ms_Tinh;
		
		public View_Duong_Not_District()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_v", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_v
		{
			get
			{
				return this._ten_v;
			}
			set
			{
				if ((this._ten_v != value))
				{
					this._ten_v = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_Duong", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ms_Duong
		{
			get
			{
				return this._ms_Duong;
			}
			set
			{
				if ((this._ms_Duong != value))
				{
					this._ms_Duong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_Tinh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ms_Tinh
		{
			get
			{
				return this._ms_Tinh;
			}
			set
			{
				if ((this._ms_Tinh != value))
				{
					this._ms_Tinh = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_ReportCustomer")]
	public partial class V_ReportCustomer
	{
		
		private string _MS_N_XUONG;
		
		private string _MS_CHA;
		
		private string _TEN_N_XUONG;
		
		private string _DIEN_THOAI;
		
		private string _DIA_CHI;
		
		private string _tendaily;
		
		private string _MS_QG;
		
		private string _MS_DUONG;
		
		private string _tenduong;
		
		private string _quan;
		
		private string _ms_city;
		
		private string _Tinh;
		
		private string _NX1;
		
		private string _MS_MAY;
		
		private string _SO_THE;
		
		private string _SERIAL_NUMBER;
		
		private string _TEN_MAY;
		
		private string _MS_NHOM_MAY;
		
		private string _TEN_NHOM_MAY;
		
		private string _MS_LOAI_MAY;
		
		private string _TEN_LOAI_MAY;
		
		public V_ReportCustomer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_N_XUONG", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string MS_N_XUONG
		{
			get
			{
				return this._MS_N_XUONG;
			}
			set
			{
				if ((this._MS_N_XUONG != value))
				{
					this._MS_N_XUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_CHA", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string MS_CHA
		{
			get
			{
				return this._MS_CHA;
			}
			set
			{
				if ((this._MS_CHA != value))
				{
					this._MS_CHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_N_XUONG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_N_XUONG
		{
			get
			{
				return this._TEN_N_XUONG;
			}
			set
			{
				if ((this._TEN_N_XUONG != value))
				{
					this._TEN_N_XUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEN_THOAI", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DIEN_THOAI
		{
			get
			{
				return this._DIEN_THOAI;
			}
			set
			{
				if ((this._DIEN_THOAI != value))
				{
					this._DIEN_THOAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this._DIA_CHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendaily", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tendaily
		{
			get
			{
				return this._tendaily;
			}
			set
			{
				if ((this._tendaily != value))
				{
					this._tendaily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_QG", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MS_QG
		{
			get
			{
				return this._MS_QG;
			}
			set
			{
				if ((this._MS_QG != value))
				{
					this._MS_QG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_DUONG", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MS_DUONG
		{
			get
			{
				return this._MS_DUONG;
			}
			set
			{
				if ((this._MS_DUONG != value))
				{
					this._MS_DUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenduong", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenduong
		{
			get
			{
				return this._tenduong;
			}
			set
			{
				if ((this._tenduong != value))
				{
					this._tenduong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string quan
		{
			get
			{
				return this._quan;
			}
			set
			{
				if ((this._quan != value))
				{
					this._quan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_city", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ms_city
		{
			get
			{
				return this._ms_city;
			}
			set
			{
				if ((this._ms_city != value))
				{
					this._ms_city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tinh
		{
			get
			{
				return this._Tinh;
			}
			set
			{
				if ((this._Tinh != value))
				{
					this._Tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NX1", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string NX1
		{
			get
			{
				return this._NX1;
			}
			set
			{
				if ((this._NX1 != value))
				{
					this._NX1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_MAY", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MS_MAY
		{
			get
			{
				return this._MS_MAY;
			}
			set
			{
				if ((this._MS_MAY != value))
				{
					this._MS_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_THE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SO_THE
		{
			get
			{
				return this._SO_THE;
			}
			set
			{
				if ((this._SO_THE != value))
				{
					this._SO_THE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIAL_NUMBER", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SERIAL_NUMBER
		{
			get
			{
				return this._SERIAL_NUMBER;
			}
			set
			{
				if ((this._SERIAL_NUMBER != value))
				{
					this._SERIAL_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_MAY", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TEN_MAY
		{
			get
			{
				return this._TEN_MAY;
			}
			set
			{
				if ((this._TEN_MAY != value))
				{
					this._TEN_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_NHOM_MAY", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MS_NHOM_MAY
		{
			get
			{
				return this._MS_NHOM_MAY;
			}
			set
			{
				if ((this._MS_NHOM_MAY != value))
				{
					this._MS_NHOM_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NHOM_MAY", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string TEN_NHOM_MAY
		{
			get
			{
				return this._TEN_NHOM_MAY;
			}
			set
			{
				if ((this._TEN_NHOM_MAY != value))
				{
					this._TEN_NHOM_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_LOAI_MAY", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MS_LOAI_MAY
		{
			get
			{
				return this._MS_LOAI_MAY;
			}
			set
			{
				if ((this._MS_LOAI_MAY != value))
				{
					this._MS_LOAI_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI_MAY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEN_LOAI_MAY
		{
			get
			{
				return this._TEN_LOAI_MAY;
			}
			set
			{
				if ((this._TEN_LOAI_MAY != value))
				{
					this._TEN_LOAI_MAY = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_BAO_TRI")]
	public partial class LOAI_BAO_TRI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MS_LOAI_BT;
		
		private string _TEN_LOAI_BT;
		
		private System.Nullable<int> _THU_TU;
		
		private int _MS_HT_BT;
		
		private string _GHI_CHU;
		
		private bool _HU_HONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMS_LOAI_BTChanging(int value);
    partial void OnMS_LOAI_BTChanged();
    partial void OnTEN_LOAI_BTChanging(string value);
    partial void OnTEN_LOAI_BTChanged();
    partial void OnTHU_TUChanging(System.Nullable<int> value);
    partial void OnTHU_TUChanged();
    partial void OnMS_HT_BTChanging(int value);
    partial void OnMS_HT_BTChanged();
    partial void OnGHI_CHUChanging(string value);
    partial void OnGHI_CHUChanged();
    partial void OnHU_HONGChanging(bool value);
    partial void OnHU_HONGChanged();
    #endregion
		
		public LOAI_BAO_TRI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_LOAI_BT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MS_LOAI_BT
		{
			get
			{
				return this._MS_LOAI_BT;
			}
			set
			{
				if ((this._MS_LOAI_BT != value))
				{
					this.OnMS_LOAI_BTChanging(value);
					this.SendPropertyChanging();
					this._MS_LOAI_BT = value;
					this.SendPropertyChanged("MS_LOAI_BT");
					this.OnMS_LOAI_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI_BT", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TEN_LOAI_BT
		{
			get
			{
				return this._TEN_LOAI_BT;
			}
			set
			{
				if ((this._TEN_LOAI_BT != value))
				{
					this.OnTEN_LOAI_BTChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAI_BT = value;
					this.SendPropertyChanged("TEN_LOAI_BT");
					this.OnTEN_LOAI_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THU_TU", DbType="Int")]
		public System.Nullable<int> THU_TU
		{
			get
			{
				return this._THU_TU;
			}
			set
			{
				if ((this._THU_TU != value))
				{
					this.OnTHU_TUChanging(value);
					this.SendPropertyChanging();
					this._THU_TU = value;
					this.SendPropertyChanged("THU_TU");
					this.OnTHU_TUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_HT_BT", DbType="Int NOT NULL")]
		public int MS_HT_BT
		{
			get
			{
				return this._MS_HT_BT;
			}
			set
			{
				if ((this._MS_HT_BT != value))
				{
					this.OnMS_HT_BTChanging(value);
					this.SendPropertyChanging();
					this._MS_HT_BT = value;
					this.SendPropertyChanged("MS_HT_BT");
					this.OnMS_HT_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(255)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this.OnGHI_CHUChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHU = value;
					this.SendPropertyChanged("GHI_CHU");
					this.OnGHI_CHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HU_HONG", DbType="Bit NOT NULL")]
		public bool HU_HONG
		{
			get
			{
				return this._HU_HONG;
			}
			set
			{
				if ((this._HU_HONG != value))
				{
					this.OnHU_HONGChanging(value);
					this.SendPropertyChanging();
					this._HU_HONG = value;
					this.SendPropertyChanged("HU_HONG");
					this.OnHU_HONGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Report_Warranty_Equipment")]
	public partial class V_Report_Warranty_Equipment
	{
		
		private string _MS_MAY_FINAL;
		
		private string _MS_N_Xuong;
		
		private string _ms_cha;
		
		private string _TEN_DAI_LY;
		
		private string _MS_Duong;
		
		private string _TENDUONG;
		
		private string _MS_Q;
		
		private string _QUAN;
		
		private string _MS_TINH;
		
		private string _TINH;
		
		private string _GHI_CHU;
		
		private string _MS_NX;
		
		private string _MS_PHIEU_BAO_TRI;
		
		private string _MS_MAY;
		
		private System.Nullable<System.DateTime> _THOI_GIAN_BAO_TRI;
		
		private System.Nullable<System.DateTime> _THOI_GIAN_SU_CO;
		
		private string _BIEN_BAN;
		
		private string _NGUOI_THUC_HIEN;
		
		private string _TEN_THIET_BI;
		
		private string _MS_NHOM_MAY;
		
		private string _TEN_NHOM_MAY;
		
		private string _MS_LOAI_MAY;
		
		private string _TEN_LOAI_MAY;
		
		private string _TEN_BO_PHAN;
		
		private string _MO_TA_CV;
		
		private string _TEN_PT;
		
		private System.Nullable<double> _SL;
		
		public V_Report_Warranty_Equipment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_MAY_FINAL", DbType="NVarChar(30)")]
		public string MS_MAY_FINAL
		{
			get
			{
				return this._MS_MAY_FINAL;
			}
			set
			{
				if ((this._MS_MAY_FINAL != value))
				{
					this._MS_MAY_FINAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_N_Xuong", DbType="NVarChar(100)")]
		public string MS_N_Xuong
		{
			get
			{
				return this._MS_N_Xuong;
			}
			set
			{
				if ((this._MS_N_Xuong != value))
				{
					this._MS_N_Xuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_cha", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string ms_cha
		{
			get
			{
				return this._ms_cha;
			}
			set
			{
				if ((this._ms_cha != value))
				{
					this._ms_cha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DAI_LY", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_DAI_LY
		{
			get
			{
				return this._TEN_DAI_LY;
			}
			set
			{
				if ((this._TEN_DAI_LY != value))
				{
					this._TEN_DAI_LY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_Duong", DbType="NVarChar(30)")]
		public string MS_Duong
		{
			get
			{
				return this._MS_Duong;
			}
			set
			{
				if ((this._MS_Duong != value))
				{
					this._MS_Duong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDUONG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENDUONG
		{
			get
			{
				return this._TENDUONG;
			}
			set
			{
				if ((this._TENDUONG != value))
				{
					this._TENDUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_Q", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MS_Q
		{
			get
			{
				return this._MS_Q;
			}
			set
			{
				if ((this._MS_Q != value))
				{
					this._MS_Q = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string QUAN
		{
			get
			{
				return this._QUAN;
			}
			set
			{
				if ((this._QUAN != value))
				{
					this._QUAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_TINH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MS_TINH
		{
			get
			{
				return this._MS_TINH;
			}
			set
			{
				if ((this._MS_TINH != value))
				{
					this._MS_TINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TINH
		{
			get
			{
				return this._TINH;
			}
			set
			{
				if ((this._TINH != value))
				{
					this._TINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(200)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this._GHI_CHU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_NX", DbType="NVarChar(100)")]
		public string MS_NX
		{
			get
			{
				return this._MS_NX;
			}
			set
			{
				if ((this._MS_NX != value))
				{
					this._MS_NX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_PHIEU_BAO_TRI", DbType="NVarChar(20)")]
		public string MS_PHIEU_BAO_TRI
		{
			get
			{
				return this._MS_PHIEU_BAO_TRI;
			}
			set
			{
				if ((this._MS_PHIEU_BAO_TRI != value))
				{
					this._MS_PHIEU_BAO_TRI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_MAY", DbType="NVarChar(30)")]
		public string MS_MAY
		{
			get
			{
				return this._MS_MAY;
			}
			set
			{
				if ((this._MS_MAY != value))
				{
					this._MS_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_GIAN_BAO_TRI", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOI_GIAN_BAO_TRI
		{
			get
			{
				return this._THOI_GIAN_BAO_TRI;
			}
			set
			{
				if ((this._THOI_GIAN_BAO_TRI != value))
				{
					this._THOI_GIAN_BAO_TRI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_GIAN_SU_CO", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOI_GIAN_SU_CO
		{
			get
			{
				return this._THOI_GIAN_SU_CO;
			}
			set
			{
				if ((this._THOI_GIAN_SU_CO != value))
				{
					this._THOI_GIAN_SU_CO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIEN_BAN", DbType="NVarChar(20)")]
		public string BIEN_BAN
		{
			get
			{
				return this._BIEN_BAN;
			}
			set
			{
				if ((this._BIEN_BAN != value))
				{
					this._BIEN_BAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOI_THUC_HIEN", DbType="NVarChar(41)")]
		public string NGUOI_THUC_HIEN
		{
			get
			{
				return this._NGUOI_THUC_HIEN;
			}
			set
			{
				if ((this._NGUOI_THUC_HIEN != value))
				{
					this._NGUOI_THUC_HIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_THIET_BI", DbType="NVarChar(255)")]
		public string TEN_THIET_BI
		{
			get
			{
				return this._TEN_THIET_BI;
			}
			set
			{
				if ((this._TEN_THIET_BI != value))
				{
					this._TEN_THIET_BI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_NHOM_MAY", DbType="NVarChar(20)")]
		public string MS_NHOM_MAY
		{
			get
			{
				return this._MS_NHOM_MAY;
			}
			set
			{
				if ((this._MS_NHOM_MAY != value))
				{
					this._MS_NHOM_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NHOM_MAY", DbType="NVarChar(250)")]
		public string TEN_NHOM_MAY
		{
			get
			{
				return this._TEN_NHOM_MAY;
			}
			set
			{
				if ((this._TEN_NHOM_MAY != value))
				{
					this._TEN_NHOM_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_LOAI_MAY", DbType="NVarChar(20)")]
		public string MS_LOAI_MAY
		{
			get
			{
				return this._MS_LOAI_MAY;
			}
			set
			{
				if ((this._MS_LOAI_MAY != value))
				{
					this._MS_LOAI_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI_MAY", DbType="NVarChar(50)")]
		public string TEN_LOAI_MAY
		{
			get
			{
				return this._TEN_LOAI_MAY;
			}
			set
			{
				if ((this._TEN_LOAI_MAY != value))
				{
					this._TEN_LOAI_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_BO_PHAN", DbType="NVarChar(50)")]
		public string TEN_BO_PHAN
		{
			get
			{
				return this._TEN_BO_PHAN;
			}
			set
			{
				if ((this._TEN_BO_PHAN != value))
				{
					this._TEN_BO_PHAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO_TA_CV", DbType="NVarChar(255)")]
		public string MO_TA_CV
		{
			get
			{
				return this._MO_TA_CV;
			}
			set
			{
				if ((this._MO_TA_CV != value))
				{
					this._MO_TA_CV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_PT", DbType="NVarChar(100)")]
		public string TEN_PT
		{
			get
			{
				return this._TEN_PT;
			}
			set
			{
				if ((this._TEN_PT != value))
				{
					this._TEN_PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Float")]
		public System.Nullable<double> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this._SL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_ReportMaintaince")]
	public partial class V_ReportMaintaince
	{
		
		private string _MS_MAY_FINAL;
		
		private string _Ten_N_Xuong;
		
		private string _MS_N_Xuong;
		
		private string _ms_cha;
		
		private string _TEN_DAI_LY;
		
		private string _MS_Duong;
		
		private string _TENDUONG;
		
		private string _MS_Q;
		
		private string _QUAN;
		
		private string _MS_TINH;
		
		private string _TINH;
		
		private string _Dien_Thoai;
		
		private string _Dia_Chi;
		
		private string _MS_NX;
		
		private string _TEN_NX;
		
		private string _MS_LOAI_MAY;
		
		private string _MO_TA_CV;
		
		private string _GHI_CHU;
		
		private string _MS_MAY;
		
		private string _MS_NHOM_MAY;
		
		private string _MODEL;
		
		private string _TEN_MAY;
		
		private System.Nullable<int> _MS_CV;
		
		private System.Nullable<System.DateTime> _NGAY_LAP;
		
		private string _MS_BO_PHAN;
		
		private string _TEN_PT;
		
		private string _TEN_1;
		
		private string _TEN_BO_PHAN;
		
		private string _TEN_NHOM_MAY;
		
		private string _MS_PT;
		
		private System.Nullable<System.DateTime> _NGAY_HOAN_THANH;
		
		private string _MS_PHIEU_BAO_TRI;
		
		private System.Nullable<int> _MS_LOAI_BT;
		
		private string _HoTen_CN;
		
		private System.Nullable<System.DateTime> _NGAY_BD_KH;
		
		private System.Nullable<double> _SL;
		
		public V_ReportMaintaince()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_MAY_FINAL", DbType="NVarChar(30)")]
		public string MS_MAY_FINAL
		{
			get
			{
				return this._MS_MAY_FINAL;
			}
			set
			{
				if ((this._MS_MAY_FINAL != value))
				{
					this._MS_MAY_FINAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_N_Xuong", DbType="NVarChar(100)")]
		public string Ten_N_Xuong
		{
			get
			{
				return this._Ten_N_Xuong;
			}
			set
			{
				if ((this._Ten_N_Xuong != value))
				{
					this._Ten_N_Xuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_N_Xuong", DbType="NVarChar(100)")]
		public string MS_N_Xuong
		{
			get
			{
				return this._MS_N_Xuong;
			}
			set
			{
				if ((this._MS_N_Xuong != value))
				{
					this._MS_N_Xuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_cha", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string ms_cha
		{
			get
			{
				return this._ms_cha;
			}
			set
			{
				if ((this._ms_cha != value))
				{
					this._ms_cha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DAI_LY", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_DAI_LY
		{
			get
			{
				return this._TEN_DAI_LY;
			}
			set
			{
				if ((this._TEN_DAI_LY != value))
				{
					this._TEN_DAI_LY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_Duong", DbType="NVarChar(30)")]
		public string MS_Duong
		{
			get
			{
				return this._MS_Duong;
			}
			set
			{
				if ((this._MS_Duong != value))
				{
					this._MS_Duong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDUONG", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENDUONG
		{
			get
			{
				return this._TENDUONG;
			}
			set
			{
				if ((this._TENDUONG != value))
				{
					this._TENDUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_Q", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MS_Q
		{
			get
			{
				return this._MS_Q;
			}
			set
			{
				if ((this._MS_Q != value))
				{
					this._MS_Q = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string QUAN
		{
			get
			{
				return this._QUAN;
			}
			set
			{
				if ((this._QUAN != value))
				{
					this._QUAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_TINH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MS_TINH
		{
			get
			{
				return this._MS_TINH;
			}
			set
			{
				if ((this._MS_TINH != value))
				{
					this._MS_TINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TINH
		{
			get
			{
				return this._TINH;
			}
			set
			{
				if ((this._TINH != value))
				{
					this._TINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dien_Thoai", DbType="NVarChar(20)")]
		public string Dien_Thoai
		{
			get
			{
				return this._Dien_Thoai;
			}
			set
			{
				if ((this._Dien_Thoai != value))
				{
					this._Dien_Thoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi", DbType="NVarChar(100)")]
		public string Dia_Chi
		{
			get
			{
				return this._Dia_Chi;
			}
			set
			{
				if ((this._Dia_Chi != value))
				{
					this._Dia_Chi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_NX", DbType="NVarChar(100)")]
		public string MS_NX
		{
			get
			{
				return this._MS_NX;
			}
			set
			{
				if ((this._MS_NX != value))
				{
					this._MS_NX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NX", DbType="NVarChar(100)")]
		public string TEN_NX
		{
			get
			{
				return this._TEN_NX;
			}
			set
			{
				if ((this._TEN_NX != value))
				{
					this._TEN_NX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_LOAI_MAY", DbType="NVarChar(20)")]
		public string MS_LOAI_MAY
		{
			get
			{
				return this._MS_LOAI_MAY;
			}
			set
			{
				if ((this._MS_LOAI_MAY != value))
				{
					this._MS_LOAI_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO_TA_CV", DbType="NVarChar(255)")]
		public string MO_TA_CV
		{
			get
			{
				return this._MO_TA_CV;
			}
			set
			{
				if ((this._MO_TA_CV != value))
				{
					this._MO_TA_CV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(250)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this._GHI_CHU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_MAY", DbType="NVarChar(30)")]
		public string MS_MAY
		{
			get
			{
				return this._MS_MAY;
			}
			set
			{
				if ((this._MS_MAY != value))
				{
					this._MS_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_NHOM_MAY", DbType="NVarChar(20)")]
		public string MS_NHOM_MAY
		{
			get
			{
				return this._MS_NHOM_MAY;
			}
			set
			{
				if ((this._MS_NHOM_MAY != value))
				{
					this._MS_NHOM_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODEL", DbType="NVarChar(50)")]
		public string MODEL
		{
			get
			{
				return this._MODEL;
			}
			set
			{
				if ((this._MODEL != value))
				{
					this._MODEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_MAY", DbType="NVarChar(255)")]
		public string TEN_MAY
		{
			get
			{
				return this._TEN_MAY;
			}
			set
			{
				if ((this._TEN_MAY != value))
				{
					this._TEN_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_CV", DbType="Int")]
		public System.Nullable<int> MS_CV
		{
			get
			{
				return this._MS_CV;
			}
			set
			{
				if ((this._MS_CV != value))
				{
					this._MS_CV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_LAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_LAP
		{
			get
			{
				return this._NGAY_LAP;
			}
			set
			{
				if ((this._NGAY_LAP != value))
				{
					this._NGAY_LAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_BO_PHAN", DbType="NVarChar(50)")]
		public string MS_BO_PHAN
		{
			get
			{
				return this._MS_BO_PHAN;
			}
			set
			{
				if ((this._MS_BO_PHAN != value))
				{
					this._MS_BO_PHAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_PT", DbType="NVarChar(100)")]
		public string TEN_PT
		{
			get
			{
				return this._TEN_PT;
			}
			set
			{
				if ((this._TEN_PT != value))
				{
					this._TEN_PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_1", DbType="NVarChar(20)")]
		public string TEN_1
		{
			get
			{
				return this._TEN_1;
			}
			set
			{
				if ((this._TEN_1 != value))
				{
					this._TEN_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_BO_PHAN", DbType="NVarChar(50)")]
		public string TEN_BO_PHAN
		{
			get
			{
				return this._TEN_BO_PHAN;
			}
			set
			{
				if ((this._TEN_BO_PHAN != value))
				{
					this._TEN_BO_PHAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NHOM_MAY", DbType="NVarChar(250)")]
		public string TEN_NHOM_MAY
		{
			get
			{
				return this._TEN_NHOM_MAY;
			}
			set
			{
				if ((this._TEN_NHOM_MAY != value))
				{
					this._TEN_NHOM_MAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_PT", DbType="NVarChar(25)")]
		public string MS_PT
		{
			get
			{
				return this._MS_PT;
			}
			set
			{
				if ((this._MS_PT != value))
				{
					this._MS_PT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_HOAN_THANH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_HOAN_THANH
		{
			get
			{
				return this._NGAY_HOAN_THANH;
			}
			set
			{
				if ((this._NGAY_HOAN_THANH != value))
				{
					this._NGAY_HOAN_THANH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_PHIEU_BAO_TRI", DbType="NVarChar(20)")]
		public string MS_PHIEU_BAO_TRI
		{
			get
			{
				return this._MS_PHIEU_BAO_TRI;
			}
			set
			{
				if ((this._MS_PHIEU_BAO_TRI != value))
				{
					this._MS_PHIEU_BAO_TRI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MS_LOAI_BT", DbType="Int")]
		public System.Nullable<int> MS_LOAI_BT
		{
			get
			{
				return this._MS_LOAI_BT;
			}
			set
			{
				if ((this._MS_LOAI_BT != value))
				{
					this._MS_LOAI_BT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen_CN", DbType="NVarChar(41)")]
		public string HoTen_CN
		{
			get
			{
				return this._HoTen_CN;
			}
			set
			{
				if ((this._HoTen_CN != value))
				{
					this._HoTen_CN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_BD_KH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_BD_KH
		{
			get
			{
				return this._NGAY_BD_KH;
			}
			set
			{
				if ((this._NGAY_BD_KH != value))
				{
					this._NGAY_BD_KH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Float")]
		public System.Nullable<double> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this._SL = value;
				}
			}
		}
	}
	
	public partial class Get_Nha_Xuong_AllResult
	{
		
		private string _ms_n_xuong;
		
		private string _ten_n_xuong;
		
		public Get_Nha_Xuong_AllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ms_n_xuong", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string ms_n_xuong
		{
			get
			{
				return this._ms_n_xuong;
			}
			set
			{
				if ((this._ms_n_xuong != value))
				{
					this._ms_n_xuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_n_xuong", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_n_xuong
		{
			get
			{
				return this._ten_n_xuong;
			}
			set
			{
				if ((this._ten_n_xuong != value))
				{
					this._ten_n_xuong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
